// Generated by CoffeeScript 2.6.1
(function() {
  var clone, graph, json, processNode, reflite;

  reflite = require('json-ref-lite');

  clone = function(obj) {
    return JSON.parse(JSON.stringify(obj));
  };

  processNode = function(node, data) {
    var edge, i, len, ref, result, results;
    result = node.process(data);
    if (result) {
      ref = node["$ref"];
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        edge = ref[i];
        results.push(processNode(edge, clone(data)));
      }
      return results;
    }
  };

  // create the graph: b<->a<-c
  json = {
    a: {
      "$ref": [
        {
          "$ref": "#/b"
        }
      ],
      process: function(data) {
        data.a = true;
        return console.dir(data);
      }
    },
    b: {
      "$ref": [
        {
          "$ref": "#/a"
        }
      ],
      process: function(data) {
        if (data.b != null) {
          return void 0; // stops flow if already processed
        }
        return data.b = true;
      }
    },
    c: {
      "$ref": [
        {
          "$ref": "#/a"
        }
      ],
      process: function(data) {
        return data.c = true;
      }
    }
  };

  graph = reflite.resolve(json);

  processNode(graph.b, {
    foo: "bar" // take b as startnode
  });

  processNode(graph.c, {
    foo: "bar" // take c as startnode
  });

  console.log("for a more advanced example see https://npmjs.org/packages/jsongraph");

}).call(this);
